name: Build and Release

on:
  release:
    types: [created]

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Zip dist directory
        run: |
          cd dist
          zip -r ../ha-card-nobreak.zip .
          cd ..
      
      - name: Upload build artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**
            ha-card-nobreak.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
